name: Build and Create Prerelease

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Bump patch version in manifest.json
        id: bump
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          jq --arg v "$NEW_VERSION" '.version = $v' manifest.json > tmp && mv tmp manifest.json
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "ci: bump version to ${{ steps.bump.outputs.new_version }}"
          git push origin main

      - name: Create ZIP package
        run: |
          mkdir -p dist
          zip -r "dist/pomoblock-${{ steps.bump.outputs.new_version }}.zip" . -x '*.git*' 'dist/*'

      - name: Create GitHub prerelease
        id: create_release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          name: ${{ steps.bump.outputs.new_version }}
          tag_name: v${{ steps.bump.outputs.new_version }}
          draft: false
          prerelease: true
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.bump.outputs.new_version }}
          tag_name: v${{ steps.bump.outputs.new_version }}
          prerelease: true
          files: dist/pomoblock-${{ steps.bump.outputs.new_version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dist/pomoblock-${{ steps.bump.outputs.new_version }}.zip
          asset_name: pomoblock-${{ steps.bump.outputs.new_version }}.zip
          asset_content_type: application/zip
